init commit
Innopolis-UAV-Team/lights_node pull request #12
Opened 2024-05-08 16:50 UTC by AsiiaPine

The module has its own separated parameters: scale, offset and enable (scale and offset was used since the measurements taken in the lab had some shift)
Timing:
- parameters update is performed with 1 Hz freq.
- data collection — 10 Hz
- data publication — 10Hz

![image](https://github.com/Innopolis-UAV-Team/lights_node/assets/70723894/35560b4d-aa1f-44a4-8ce0-ac647e344c9e)

2024-05-15 09:44 UTC, PonomarevDA requested changes
The timestamp has a random value. It is serialized incorrectly. Everything else seems fine.

```c++
uint8_t offset = 0;
auto timestamp = obj->timestamp;
canardEncodeScalar(buffer, 56, offset, &timestamp);
offset += 56;
```

2024-05-15 09:44 UTC, PonomarevDA commented on Src/dronecan_application/modules/RangeFinder/params.yaml
> +  max: 1000
Let's keep only 2 parameters here at the moment:
- range.enable
- range.id

Offset parameter can be useful, but it is actually slightly more complicated that a single parameter. An autopilot needs pos_x, pos_y, pos_z, pitch, roll values to calculate the flight height. This configuration is done on the PX4 side with EKF2_RNG_* parameters. More details: https://docs.px4.io/main/en/sensor/rangefinders.html#configuration

No doubt, we can duplicate these parameters here and apply some math to calculate the required distance, but it requires a few times more lines of code and I'm not sure we will even use it some day. PX4 parameters are sufficient for us.

As I see the scale parameter is redundant here. Usually, a sensor estimate the distance quite precisely withing his operating conditions and doesn't need an additional calibration.

2024-05-15 09:44 UTC, PonomarevDA commented on Src/dronecan_application/modules/RangeFinder/params.yaml
> +  default: 0
Let's enable it by default

2024-05-16 07:39 UTC, AsiiaPine commented on Src/dronecan_application/modules/RangeFinder/params.yaml
> +  max: 1000
Done

2024-05-16 12:49 UTC, PonomarevDA requested changes
Good. Please, just update the submodule to the main branch because `This commit does not belong to any branch on this repository`.

2024-05-20 18:33 UTC, PonomarevDA approved these changes

2024-05-20 18:35 UTC, merged